spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HackingPintu/config-server
          clone-on-start: true

server:
  port: 1805